# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = '''
[┌\($username@$hostname\)─\($character\)─\($time\)](white)
[│](white)$directory$rust$package
[└─\($directory\)>](white)'''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[hostname]
ssh_only = false
format = '[$hostname](bold blue)'
trim_at = '.companyname.com'
disabled = false

[username]
style_user = 'bold blue'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }
